import assert from 'node:assert/strict';
import { MACFIT_QUESTIONS, normalizeMacfitPhone, validateMacfitSubmission } from '../lib/macfit-funnel.ts';
import { createMacfitAccess, readMacfitAccess } from '../lib/macfit-access.ts';
process.env.MACFIT_ACCESS_SECRET = 'local-test-only';
const valid = { firstName: 'Test', lastName: 'Salon', email: 'test@example.com', phone: '0532 000 00 00', instagram: '@test.salon', answers: Object.fromEntries(MACFIT_QUESTIONS.map(q => [q.key, q.options[0]])) };
assert.equal(normalizeMacfitPhone('0532 000 00 00'), '+905320000000');
for (const bad of ['1234567890', '+445320000000', 'abc05320000000', '90005320000000']) assert.equal(normalizeMacfitPhone(bad), null);
assert.ok(validateMacfitSubmission(valid).data);
assert.ok(validateMacfitSubmission({ ...valid, answers: {} }).error);
assert.ok(validateMacfitSubmission({ ...valid, phone: '1234' }).error);
assert.ok(validateMacfitSubmission({ ...valid, answers: { ...valid.answers, capacity: 'invented' } }).error);
assert.ok(validateMacfitSubmission({ ...valid, answers: { ...valid.answers, problem: 'Başka bir sorun yaşıyorum.' } }).error);
assert.ok(validateMacfitSubmission({ ...valid, answers: { ...valid.answers, problem: 'Başka bir sorun yaşıyorum.', problemOther: 'Detay' } }).data);
assert.ok(validateMacfitSubmission(null).error);
const id = '00000000-0000-4000-8000-000000000001';
const token = createMacfitAccess(id);
assert.equal(readMacfitAccess(token), id);
assert.equal(readMacfitAccess(token.slice(0, -1) + (token.endsWith('0') ? '1' : '0')), null);
assert.equal(readMacfitAccess('1'), null);
assert.equal(readMacfitAccess(undefined), null);
console.log('MACFit validation + access checks passed');
